import { EventSchedule, EventTemplate, AppSettings } from '../types';

export const DEFAULT_SETTINGS: AppSettings = {
  general: {
    language: 'en',
    timeFormat: '12h',
    dateFormat: 'YYYY-MM-DD',
    autoRestoreLastSession: true,
  },
  timer: {
    displayFormat: 'MM:SS',
    countDownBehavior: 'standard',
    autoAdvanceOnZero: false,
    overtimeAlertThresholds: [60, 180, 300],
    flashOnOvertime: true,
  },
  alerts: {
    soundEnabled: true,
    masterVolume: 0.75,
    selectedSound: 'soft-chime',
    visualFlash: true,
    defaultWarningTimes: [600, 300, 60, 10], // 10m, 5m, 1m, 10s
  },
  presenter: {
    theme: 'minimal-dark',
    mode: 'event',
    showNextSegment: true,
    showEventName: true,
    showClock: true,
    showTimeline: true,
    fontSizeMultiplier: 1.0,
    customMessage: 'Welcome to the Sanctuary. Please silence mobile devices.',
    showCustomMessage: false,
  },
  panicButton: {
    label: '+5 MIN QUICK BUFFER',
    action: 'add_5m',
    requireConfirmation: true,
  },
  keyboardShortcuts: {
    startPause: 'Space',
    nextSegment: 'KeyN',
    prevSegment: 'KeyP',
    resetSegment: 'KeyR',
    add1Min: 'Equal', // + key
    sub1Min: 'Minus', // - key
    add5Min: 'BracketRight',
    sub5Min: 'BracketLeft',
    togglePresenter: 'KeyF',
    muteAlerts: 'KeyM',
    focusMode: 'KeyO',
  },
};

export const BUILT_IN_TEMPLATES: EventTemplate[] = [
  {
    id: 'tpl-sunday-worship',
    name: 'Sunday Worship Service',
    description: 'Standard liturgical weekend service with praise, sermon, announcements, and benediction.',
    category: 'Church',
    estimatedTotalDurationSeconds: 85 * 60, // 1h 25m
    defaultTheme: 'church',
    segments: [
      {
        order: 1,
        name: 'Opening Prayer',
        description: 'Call to worship and invocation',
        plannedDurationSeconds: 5 * 60,
        speaker: 'Associate Pastor',
        category: 'Prayer',
        colorTag: 'amber',
        warningTimesSeconds: [180, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
      {
        order: 2,
        name: 'Praise & Worship',
        description: 'Congregational praise songs and choir',
        plannedDurationSeconds: 15 * 60,
        speaker: 'Worship Team',
        category: 'Worship',
        colorTag: 'blue',
        warningTimesSeconds: [300, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
      {
        order: 3,
        name: 'Announcements & Welcome',
        description: 'Visitor greeting, upcoming events and ministry news',
        plannedDurationSeconds: 7 * 60,
        speaker: 'Media Host',
        category: 'Announcements',
        colorTag: 'emerald',
        warningTimesSeconds: [120, 30],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
      {
        order: 4,
        name: 'Special Presentation / Testimony',
        description: 'Youth ministry highlight or missionary spotlight',
        plannedDurationSeconds: 10 * 60,
        speaker: 'Guest Speaker',
        category: 'Presentation',
        colorTag: 'purple',
        warningTimesSeconds: [180, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: true,
        isSkipped: false,
        segmentType: 'TIMER',
      },
      {
        order: 5,
        name: 'Sermon / Message',
        description: 'Main scriptural teaching and exposition',
        plannedDurationSeconds: 35 * 60,
        speaker: 'Senior Pastor',
        category: 'Speech',
        colorTag: 'rose',
        warningTimesSeconds: [600, 300, 60, 10],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'SPEAKER',
      },
      {
        order: 6,
        name: 'Offering & Intercession',
        description: 'Tithes, benevolence offering, and prayer over requests',
        plannedDurationSeconds: 8 * 60,
        speaker: 'Deacon Board',
        category: 'Ceremony',
        colorTag: 'indigo',
        warningTimesSeconds: [120, 30],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
      {
        order: 7,
        name: 'Closing Prayer & Benediction',
        description: 'Dismissal blessing and postlude song',
        plannedDurationSeconds: 5 * 60,
        speaker: 'Senior Pastor',
        category: 'Prayer',
        colorTag: 'amber',
        warningTimesSeconds: [60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
    ],
  },
  {
    id: 'tpl-tech-conference',
    name: 'Tech Conference Keynote Track',
    description: 'Conference keynote, sponsor keynote, technical deep-dive, and live panel Q&A.',
    category: 'Conference',
    estimatedTotalDurationSeconds: 120 * 60, // 2h
    defaultTheme: 'corporate',
    segments: [
      {
        order: 1,
        name: 'Opening Keynote Address',
        description: 'Vision statement and industry trends',
        plannedDurationSeconds: 45 * 60,
        speaker: 'Dr. Elena Vance, CTO',
        category: 'Speech',
        colorTag: 'blue',
        warningTimesSeconds: [600, 300, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'SPEAKER',
      },
      {
        order: 2,
        name: 'Product Architecture Showcase',
        description: 'Live code walkthrough and benchmark demos',
        plannedDurationSeconds: 30 * 60,
        speaker: 'Lead Architect',
        category: 'Presentation',
        colorTag: 'purple',
        warningTimesSeconds: [300, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'SPEAKER',
      },
      {
        order: 3,
        name: 'Audience Q&A & Panel Discussion',
        description: 'Moderated panel with mic runners',
        plannedDurationSeconds: 30 * 60,
        speaker: 'Panelists & Moderator',
        category: 'Speech',
        colorTag: 'emerald',
        warningTimesSeconds: [300, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
      {
        order: 4,
        name: 'Break & Networking Transition',
        description: 'Stage turnover and attendee coffee break',
        plannedDurationSeconds: 15 * 60,
        speaker: 'Stage Crew',
        category: 'Break',
        colorTag: 'neutral',
        warningTimesSeconds: [180, 60],
        soundEnabled: true,
        autoAdvance: true,
        isOptional: false,
        isSkipped: false,
        segmentType: 'BREAK',
      },
    ],
  },
  {
    id: 'tpl-wedding-ceremony',
    name: 'Formal Wedding Ceremony',
    description: 'Prelude, procession, readings, vows, ring exchange, and pronouncement.',
    category: 'Wedding',
    estimatedTotalDurationSeconds: 45 * 60,
    defaultTheme: 'elegant',
    segments: [
      {
        order: 1,
        name: 'Prelude & Seating of Grandparents',
        description: 'Acoustic instrumental music',
        plannedDurationSeconds: 10 * 60,
        speaker: 'Musicians',
        category: 'Media',
        colorTag: 'purple',
        warningTimesSeconds: [120],
        soundEnabled: false,
        autoAdvance: true,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
      {
        order: 2,
        name: 'Bridal Processional',
        description: 'Entrance of the bridal party and bride',
        plannedDurationSeconds: 5 * 60,
        speaker: 'Officiant',
        category: 'Ceremony',
        colorTag: 'rose',
        warningTimesSeconds: [60],
        soundEnabled: false,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
      {
        order: 3,
        name: 'Homily & Personal Vows',
        description: 'Message from the officiant and exchanged vows',
        plannedDurationSeconds: 15 * 60,
        speaker: 'Officiant & Couple',
        category: 'Speech',
        colorTag: 'amber',
        warningTimesSeconds: [180, 60],
        soundEnabled: false,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'SPEAKER',
      },
      {
        order: 4,
        name: 'Ring Exchange & Pronouncement',
        description: 'Exchanging rings, first kiss, and introduction',
        plannedDurationSeconds: 10 * 60,
        speaker: 'Officiant',
        category: 'Ceremony',
        colorTag: 'emerald',
        warningTimesSeconds: [60],
        soundEnabled: false,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
      {
        order: 5,
        name: 'Recessional',
        description: 'Couple departure and guest dismissal',
        plannedDurationSeconds: 5 * 60,
        speaker: 'Wedding Coordinator',
        category: 'Break',
        colorTag: 'blue',
        warningTimesSeconds: [60],
        soundEnabled: false,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
    ],
  },
  {
    id: 'tpl-corporate-all-hands',
    name: 'Quarterly All-Hands Meeting',
    description: 'Executive briefing, milestone accomplishments, department updates, and open mic.',
    category: 'Corporate',
    estimatedTotalDurationSeconds: 60 * 60,
    defaultTheme: 'corporate',
    segments: [
      {
        order: 1,
        name: 'State of the Company',
        description: 'CEO remarks on quarterly OKRs and vision',
        plannedDurationSeconds: 20 * 60,
        speaker: 'Chief Executive Officer',
        category: 'Speech',
        colorTag: 'blue',
        warningTimesSeconds: [300, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'SPEAKER',
      },
      {
        order: 2,
        name: 'Product & Engineering Highlights',
        description: 'Major releases and customer feedback review',
        plannedDurationSeconds: 15 * 60,
        speaker: 'VP Product',
        category: 'Presentation',
        colorTag: 'purple',
        warningTimesSeconds: [180, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'SPEAKER',
      },
      {
        order: 3,
        name: 'Employee Recognition & Spotlight',
        description: 'Values in action awards and new hire welcome',
        plannedDurationSeconds: 10 * 60,
        speaker: 'Head of People',
        category: 'Ceremony',
        colorTag: 'amber',
        warningTimesSeconds: [120, 30],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
      {
        order: 4,
        name: 'Unfiltered AMA & Q&A',
        description: 'Live Slido questions and open microphone',
        plannedDurationSeconds: 15 * 60,
        speaker: 'Executive Staff',
        category: 'Speech',
        colorTag: 'rose',
        warningTimesSeconds: [300, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
    ],
  },
  {
    id: 'tpl-award-gala',
    name: 'Annual Honors Gala & Awards',
    description: 'Red carpet opening, dinner course, category presentations, and acceptance speeches.',
    category: 'Award Ceremony',
    estimatedTotalDurationSeconds: 150 * 60,
    defaultTheme: 'cinema',
    segments: [
      {
        order: 1,
        name: 'Opening Monologue & Welcome',
        description: 'Master of Ceremonies welcome and event sponsor thanks',
        plannedDurationSeconds: 12 * 60,
        speaker: 'Master of Ceremonies',
        category: 'Speech',
        colorTag: 'amber',
        warningTimesSeconds: [180, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'SPEAKER',
      },
      {
        order: 2,
        name: 'Community Impact Awards (3 Nominees)',
        description: 'Video roll and winner speech',
        plannedDurationSeconds: 20 * 60,
        speaker: 'Presenter Duo',
        category: 'Ceremony',
        colorTag: 'purple',
        warningTimesSeconds: [300, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'TIMER',
      },
      {
        order: 3,
        name: 'Musical Interlude & Dinner Turnover',
        description: 'Live quartet performance',
        plannedDurationSeconds: 40 * 60,
        speaker: 'Ensemble',
        category: 'Media',
        colorTag: 'blue',
        warningTimesSeconds: [300, 60],
        soundEnabled: false,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'BREAK',
      },
      {
        order: 4,
        name: 'Lifetime Achievement Presentation',
        description: 'Honoree retrospective video and speech',
        plannedDurationSeconds: 25 * 60,
        speaker: 'Board Chair & Honoree',
        category: 'Speech',
        colorTag: 'rose',
        warningTimesSeconds: [300, 60],
        soundEnabled: true,
        autoAdvance: false,
        isOptional: false,
        isSkipped: false,
        segmentType: 'SPEAKER',
      },
    ],
  },
];

export const DEMO_EVENT: EventSchedule = {
  id: 'evt-demo-sunday-service',
  name: 'Sunday Worship Service',
  date: new Date().toISOString().split('T')[0],
  startTime: '09:00',
  location: 'Main Sanctuary & Online Broadcast',
  organizer: 'Production & Liturgy Team',
  description: 'Full weekly congregation gathering with choral worship, communion, sermon, and benediction.',
  currentSegmentIndex: 0,
  status: 'READY',
  activeScenario: 'NORMAL',
  scenarioAdjustments: {
    shortReductionPercent: 15,
    emergencyReductionPercent: 35,
  },
  totalPlannedDurationSeconds: (5 + 15 + 7 + 10 + 35 + 8 + 5) * 60, // 85 mins = 5100s
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  segments: [
    {
      id: 'seg-1',
      eventId: 'evt-demo-sunday-service',
      order: 1,
      name: 'Opening Prayer',
      description: 'Invocation and scripture call to worship',
      plannedDurationSeconds: 5 * 60,
      speaker: 'Pastor Marcus Vance',
      category: 'Prayer',
      colorTag: 'amber',
      warningTimesSeconds: [180, 60],
      soundEnabled: true,
      autoAdvance: false,
      isOptional: false,
      isSkipped: false,
      segmentType: 'TIMER',
    },
    {
      id: 'seg-2',
      eventId: 'evt-demo-sunday-service',
      order: 2,
      name: 'Praise & Worship',
      description: 'Congregational singing (4 songs)',
      plannedDurationSeconds: 15 * 60,
      speaker: 'Worship Band & Choir',
      category: 'Worship',
      colorTag: 'blue',
      warningTimesSeconds: [300, 60],
      soundEnabled: true,
      autoAdvance: false,
      isOptional: false,
      isSkipped: false,
      segmentType: 'TIMER',
    },
    {
      id: 'seg-3',
      eventId: 'evt-demo-sunday-service',
      order: 3,
      name: 'Announcements',
      description: 'Welcome new guests and community ministry opportunities',
      plannedDurationSeconds: 7 * 60,
      speaker: 'Host Sarah Jenkins',
      category: 'Announcements',
      colorTag: 'emerald',
      warningTimesSeconds: [120, 30],
      soundEnabled: true,
      autoAdvance: false,
      isOptional: false,
      isSkipped: false,
      segmentType: 'TIMER',
    },
    {
      id: 'seg-4',
      eventId: 'evt-demo-sunday-service',
      order: 4,
      name: 'Special Presentation',
      description: 'Summer mission trip documentary video and testimony',
      plannedDurationSeconds: 10 * 60,
      speaker: 'Youth Leadership',
      category: 'Presentation',
      colorTag: 'purple',
      warningTimesSeconds: [180, 60],
      soundEnabled: true,
      autoAdvance: false,
      isOptional: true,
      isSkipped: false,
      segmentType: 'TIMER',
    },
    {
      id: 'seg-5',
      eventId: 'evt-demo-sunday-service',
      order: 5,
      name: 'Sermon',
      description: 'Title: "Walking in Purpose: The Courage to Stand"',
      plannedDurationSeconds: 35 * 60,
      speaker: 'Senior Pastor David Hall',
      category: 'Speech',
      colorTag: 'rose',
      warningTimesSeconds: [600, 300, 60, 10],
      soundEnabled: true,
      autoAdvance: false,
      isOptional: false,
      isSkipped: false,
      segmentType: 'SPEAKER',
    },
    {
      id: 'seg-6',
      eventId: 'evt-demo-sunday-service',
      order: 6,
      name: 'Offering',
      description: 'Tithes, giving video, and stewardship prayer',
      plannedDurationSeconds: 8 * 60,
      speaker: 'Deacon Committee',
      category: 'Ceremony',
      colorTag: 'indigo',
      warningTimesSeconds: [120, 30],
      soundEnabled: true,
      autoAdvance: false,
      isOptional: false,
      isSkipped: false,
      segmentType: 'TIMER',
    },
    {
      id: 'seg-7',
      eventId: 'evt-demo-sunday-service',
      order: 7,
      name: 'Closing Prayer',
      description: 'Benediction blessing and musical dismissal',
      plannedDurationSeconds: 5 * 60,
      speaker: 'Senior Pastor David Hall',
      category: 'Prayer',
      colorTag: 'amber',
      warningTimesSeconds: [60],
      soundEnabled: true,
      autoAdvance: false,
      isOptional: false,
      isSkipped: false,
      segmentType: 'TIMER',
    },
  ],
};
